language: csharp 
solution: n4.net.extensions.sln
install:
  - nuget restore n4.net.extensions.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release n4.net.extensions.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Extensions/Test/bin/Release/N4.Net.Extensions.Test.dll